version: 0.2

phases: 
    pre_build: 
      commands:
      - npm install
      - npm test
    build:
      commands:
        - npm run webpack
    

artifacts:
    files:
      - index.html
      - favicon.ico
      - dtResume_it_V1.31.19.pdf
      - styles/*
      - images/*
      - dist/bundle.js