version: 0.1

phases: 
    build:
      commands:
    - echo Nothing to do yet

artifacts:
    files:
      - index.html
      - favicon.ico
      - dtResume_it-V1.31.19.pdf
      - styles/*
      - images/*